### ISSUE TITLE
Get duck duck go fixed results

### ISSUE THREAD

**Issue by MeNsaaH** [bisoncorps/search-engine-parser#10]
With other Search engines, we are able to add offsets for page numbers and number of results to return. DuckDuckGo however does not seem straight forward. We should look for the accurate way to make the requests to duckduckgo

**Comment by ashokkumarta** [comment]
Checked the behavior of duckduckgo page navigation. 

The URL below available as both the POST and GET methods returns results based on page position.

https://duckduckgo.com/html/?q={query}&s={start}&dc={offset}&v=l&o=json&api=/d.js

with start parameter being
- 0 for 1st page  
- 30 for 2nd page 
- 80 for 3rd page 
- 130 for 4th page
- ... increases by 50 for each subsequent page

and offset value is one less than start value for forward navigation (this value does not influence search results, but is needed as a parameter.

Other parameters in the URL have fixed values. 

URLs for a sample query string "Hello"
[Page 1](https://duckduckgo.com/html/?q=hello&s=0&dc=-1&v=l&o=json&api=/d.js)
[Page 2](https://duckduckgo.com/html/?q=hello&s=30&dc=29&v=l&o=json&api=/d.js)
[Page 3](https://duckduckgo.com/html/?q=hello&s=80&dc=79&v=l&o=json&api=/d.js)
[Page 4](https://duckduckgo.com/html/?q=hello&s=130&dc=129&v=l&o=json&api=/d.js)

Checking the code to handle Page navigation for duckduckgo engine.

**Comment by MeNsaaH** [comment]
That's nice. Can you make a PR?

**Comment by ashokkumarta** [comment]
Create PR #66.
