### ISSUE TITLE
Event Loop is already running error.

### ISSUE THREAD

**Issue by varunkhuran** [bisoncorps/search-engine-parser#112]
I used the package out of the box and found that there an error is raised when calling the search function.  With a quick stackoverflow search, I fixed the error by using nest_asyncio; however, I was wondering if there is a way to fix this error without using nest asyncio since it seems like the developers of search_engine_parser intended on using asyncio (I am not incredibly familiar with asyncio).

Just for reference, I am using Jupyter Notebook and Python 3.8.  Here is the code with and without the nest_asyncio code.

<img width="534" alt="Screen Shot 2020-09-16 at 11 13 42 AM" src="https://user-images.githubusercontent.com/69031184/93377005-4e4ba680-f80f-11ea-94b4-bed848b02d27.png">
<img width="533" alt="Screen Shot 2020-09-16 at 11 13 54 AM" src="https://user-images.githubusercontent.com/69031184/93377015-51469700-f80f-11ea-85de-a9da82a09ad8.png">
<img width="537" alt="Screen Shot 2020-09-16 at 11 14 15 AM" src="https://user-images.githubusercontent.com/69031184/93377020-51df2d80-f80f-11ea-999f-0c58d256cea8.png">

**Comment by deven96** [comment]
Version information?

**Comment by varunkhuran** [comment]
<img width="986" alt="Screen Shot 2020-09-20 at 8 05 10 AM" src="https://user-images.githubusercontent.com/69031184/93714525-18146c80-fb18-11ea-9792-777bd2bb44c1.png">

This is the version information for the search-engine-parser and its dependencies.

**Comment by deven96** [comment]
From what I can see, this issue occurs mainly with jupyter notebooks right? @varunkhuran
Perhaps we have to add some documentation warning people who want to use notebooks with this
Would you consider contributing ?

**Comment by dodo325** [comment]
> From what I can see, this issue occurs mainly with jupyter notebooks right? @varunkhuran
> Perhaps we have to add some documentation warning people who want to use notebooks with this
> Would you consider contributing ?

![image](https://user-images.githubusercontent.com/7831197/94605080-407f3200-02a1-11eb-8c15-22c2628481b2.png)
No, not only in notebooks! CLI examples from README don't work either.

**Comment by varunkhuran** [comment]
I can try to contribute but at the moment, I am a bit too busy with grad school starting up.  I think the main fix is to put a disclaimer about using nest_asyncio.

Sorry for the late response.

**Comment by gaardhus** [comment]
Doing the following will solve the problem.
```
$ pip install nest_asyncio
$ python
>>> import nest_asyncio
>>> nest_asyncio.apply()
```
