### ISSUE TITLE
Search engine parser broken

### ISSUE THREAD

**Issue by jkthe1** [bisoncorps/search-engine-parser#115]
**Describe the bug**

**To Reproduce**
1. Open python console to 
2. Import search_engine_parser
3. Search using .... Engine

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Python Version [e.g. 3.6.5]
 - Search-engine-parser version [e.g. 0.5.1]

**Additional context**

**Comment by deven96** [comment]
Please fill in the template for the issue @jkthe1

**Comment by deven96** [comment]
Replica of #114
