### ISSUE TITLE
The authenticity of host 'github.com can't be established when cloning the repo

### ISSUE THREAD

**Issue by 07416** [bisoncorps/search-engine-parser#116]
**Describe the bug**
I receive the error `The authenticity of host 'github.com (140.82.121.3)' can't be established.` when cloning the repo by running `git clone git@github.com:bisoncorps/search-engine-parser.git`

**To Reproduce**
1. run `git clone git@github.com:bisoncorps/search-engine-parser.git`
2. see the error

**Expected behavior**
The repo is cloned successfully.

**Desktop (please complete the following information):**
 - OS: Fedora release 32 (Thirty Two)
 - Python 3.8.5
 - Search-engine-parser version: N/A, https://github.com/bisoncorps/search-engine-parser/commit/64983845ad6615bd9009e3c74149ab5d30fc6d5a

**Additional context**
full error:

```
Cloning into 'search-engine-parser'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

**Comment by deven96** [comment]
Tried installing using https instead of ssh @07416 
`git clone https://github.com/bisoncorps/search-engine-parser`
