### ISSUE TITLE
   NoResultOrTrafficError

### ISSUE THREAD

**Issue by imadraude** [bisoncorps/search-engine-parser#118]
when used search_engine_parser in telethon userbot for telegram i get this error

raise NoResultsOrTrafficError(
search_engine_parser.core.exceptions.NoResultsOrTrafficError: The returned results could not be parsed. This might be due to site updates or server errors. Drop an issue at https://github.com/bisoncorps/search-engine-parser if this persists

**Comment by deven96** [comment]
Upgrade to version 0.6.2
