### ISSUE TITLE
Prevent search engine failure

### ISSUE THREAD

**Issue by noman00910** [bisoncorps/search-engine-parser#119]
The search engine fails after making search queries between 100 to 120.
It shows the following error message: "Google engine failure", because of unusual traffic.
This can be avoided by adding proxies I guess.
I have tried to make changes in the base file and google engine file through "Requests proxies" and "SOCKS5" but it didn't work.
@deven96 suggested me to do it through aiohttp requests but there is no success.
Apply some piece of code through which we can add some paid proxies so Google Engine will not flag it unusual traffic or something.

**Comment by MeNsaaH** [comment]
Adding proxies for extra requests when unusual traffic happens has always been part of the plan for search-engine-parser as referenced by #1 . We have to think through the architectures for request proxies. What is your approach like? You can drop sample codes too

**Comment by noman00910** [comment]
yes, it can be done through sessions and it can be implemented when clearing cookies in the base file I guess.
![Screenshot_1](https://user-images.githubusercontent.com/56790293/97832546-e71d7f00-1cf4-11eb-88f7-92ce42e69138.jpg)

**Comment by MeNsaaH** [comment]
We however don't use request. But it's basically the same as https://docs.aiohttp.org/en/stable/client_advanced.html?highlight=proxy#proxy-support

**Comment by MeNsaaH** [comment]
You could send a PR
