### ISSUE TITLE
With Google search, How to controls the number of results shown?

### ISSUE THREAD

**Issue by LeMoussel** [bisoncorps/search-engine-parser#121]
In Google's search string parameters, there is `num=xx` parameter
This parameter determines the number of results to show per page. Use in combination with the page parameter to implement pagination. 
The maximum number of results Google return per request is 100 for all search_type values aside from places, where the limit is 20 per request (a Google-imposed limitation). 
These must be a numeric value, and can be anything up to 100. Doesn't work with fractions. I've tried.

It seems that this parameter (and others?) is not processed when creating the Google search url.
```
  from search_engine_parser.core.engines.google import Search as GoogleSearch
  gsearch = GoogleSearch()
  gresults = gsearch.search(query='search-engine-parser', page=1, cache=True, num=100)
```

A solution could be that:
```
  import pprint
  from search_engine_parser.core.engines.google import Search as GoogleSearch

  class MyGoogleSearch(GoogleSearch):
    def __init__(self):
        super().__init__()

    def get_params(self, query=None, offset=None, page=None, **kwargs):
        # Default parameters
        params = {
          "start": (page-1) * 10,
          "q": query,
          "gbv": 1
        }
        # Additional parameters
        for key, value in kwargs.items():
          params[key] = value

        return params

  gsearch = MyGoogleSearch()
  gresults = gsearch.search(query='search-engine-parser', page=1, cache=True, num=100)
  for index, result in enumerate(gresults):
      print(f"-------------{index}------------")
      pprint.pprint(result)

```

**Comment by MeNsaaH** [comment]
@LeMoussel, during the implementation for the search engines, we realized some search engines return inconsistent number of results during the search. As such, it'll be difficult to implement a feature that requires a certain number number to be returned. The current implementation returns results based on pages, you can use a loop to get as much number of results as you want.
