### ISSUE TITLE
Up to date random UA via real world browser usage statistic

### ISSUE THREAD

**Issue by LeMoussel** [bisoncorps/search-engine-parser#122]
I think the list of user agents is too small ([USER_AGENT_LIST](https://github.com/bisoncorps/search-engine-parser/blob/master/search_engine_parser/core/utils.py#L10)).

In other projects, I use (successfully) this library: [fake-user agent](https://github.com/hellysmile/fake-useragent). Up to date simple useragent faker with real world database.

In `utils.py`, `get_rand_user_agent()` maybe like this :
```
from fake_useragent import UserAgent

def get_rand_user_agent():
   ua = UserAgent()
   # Return random UA via real world browser usage statistic
   return ua.random
```

**Comment by deven96** [comment]
Would you mind opening a PR to effect this? @LeMoussel
