### ISSUE TITLE
Runtime error when using parser in WEbserver or jupyter notebook due to Asyncio.

### ISSUE THREAD

**Issue by Adriman2** [bisoncorps/search-engine-parser#125]
**Describe the bug**
“RuntimeError: This event loop is already running” when calling .search() method. This is a common error when using a WebServer, Jupyter Notebook or GUI due to that Asyncio does not allow its event loop to be nested. 
I fixed the error by adding 

import nest_asyncio
nest_asyncio.apply

to the __init__ of the package. I'm not sure if this is the best approach. 

**To Reproduce**
1. Create a notebook 
2. Copy example code
3. See 'Runtime error'

import nest_asyncio
nest_asyncio.apply()

**Expected behavior**

Console logs a Runtime error in base.py file. Where Asyncio is used in row [265]: asyncio.get_event_loop()  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version 3.7
 - Search-engine-parser version  0.6.2

**Comment by deven96** [comment]
This seems to be a recurring issue pointed out by others @MeNsaaH . Would you mind opening a PR to send your fix @Adriman2 ?

**Comment by MeNsaaH** [comment]
I'll be working on a fix for this later.

**Comment by MeNsaaH** [comment]
Closing this issue as this is a JupyterNotebook issue. To get around it add this to your notebook
```bash
!pip install nest-asyncio
```

```python
import nest_asyncio
nest_asyncio.apply()
```

Jupyter notebook already started is already running on the event loop. Using nest will allow search-engine asyncio to create a nested event loop.

**Comment by deven96** [comment]
Could we add it to the readme perhaps? @MeNsaaH

**Comment by MeNsaaH** [comment]
Sure I'll add it
