### ISSUE TITLE
Extract actual page URL from results (GoogleSearch)

### ISSUE THREAD

**Issue by pgrandinetti** [bisoncorps/search-engine-parser#128]
Hi--I am wondering if there's already a built-in way to extract the actual page URL from the results of the search.

Example: A GoogleSearch returns

```
https://google.com/url?q=https://www.simplyrecipes.com/recipes/spaghetti_alla_carbonara/&sa=U&ved=2ahUKEwiZz6bahe7uAhU9RDABHTISDroQFnoECAYQAg&usg=AOvVaw05E1NKVreZ6ImGI3IbvN9o
```

and the URL to use would be `https://www.simplyrecipes.com/recipes/spaghetti_alla_carbonara/`.

Is this already implemented?
Thanks.

**Comment by deven96** [comment]
This is currently not been implemented but should not be difficult using urlparse. Would you mind implementing it @pgrandinetti ?

**Comment by pgrandinetti** [comment]
@deven96 Sure I can give it a try. Can you please direct me about where this should go (what module/class) and what's a good name for it?

**Comment by deven96** [comment]
Should go under `search_engine_parser.core.google` in the `parse_url` function. Editing that function to parse out the precise url should give us the behaviour we want @pgrandinetti

**Comment by pgrandinetti** [comment]
OK let's start with that, though I think it should be done for all engines that you have it. I didn't look at the others yet.

**Comment by deven96** [comment]
Yeah let's go with this to begin with @pgrandinetti
