### ISSUE TITLE
Is this a typo/bug?

### ISSUE THREAD

**Issue by pgrandinetti** [bisoncorps/search-engine-parser#129]
https://github.com/bisoncorps/search-engine-parser/blob/e8eca7e6a316c4efaeead45019262e7c0231d7e6/search_engine_parser/core/engines/google.py#L69

**Comment by deven96** [comment]
Should be a bug. Cc @MeNsaaH

**Comment by MeNsaaH** [comment]
Yes.  @pgrandinetti can you open A PR?

**Comment by deven96** [comment]
@all-contributors please add @pgrandinetti for code and bug fix
