### ISSUE TITLE
Add YouTube Engine

### ISSUE THREAD

**Issue by deven96** [bisoncorps/search-engine-parser#13]
Youtube Engine should be capable of scraping and returning links, titles and descriptions to the individual videos with option of downloading the videos (when using the CLI)

**Comment by MeNsaaH** [comment]
Video download should be done using[Youtube dl](https://github.com/ytdl-org/youtube-dl/) or in order ways a documentation on how to use with [Youtube dl](https://github.com/ytdl-org/youtube-dl/) should be added

**Comment by PalAditya** [comment]
Do you mean that if an id is passed to the YouTube URL, these metadata should be returned for that particular video, or do you plan to support the case of returning default 10 (for example) results from home page if no id is supplied?

**Comment by MeNsaaH** [comment]
When the number of results requested in 1, the meta data should be returned and be downloadable using an integration with youtube-dl

**Comment by AvinashReddy3108** [comment]
Uh, would it not need the YouTube Data API key for searching stuff ?

**Comment by MeNsaaH** [comment]
We are scraping not searching. I think it's a bit different
