### ISSUE TITLE
Title and Description mixed up in google results

### ISSUE THREAD

**Issue by pgrandinetti** [bisoncorps/search-engine-parser#135]
**Describe the bug**
`'description'` and `'title'` are switched in results from GoogleSearch

**To Reproduce**
```
In [1]: from search_engine_parser.core.engines.google import Search as GoogleSearch

In [2]: gsearch = GoogleSearch()

In [3]: query = 'the invention of the wheel'

In [4]: gres = gsearch.search(query=query, hl='en')

In [5]: gres['links'][0]
Out[5]: 'https://www.smithsonianmag.com/science-nature/a-salute-to-the-wheel-31805121/'

In [6]: gres['titles'][0]
Out[6]: "The first wheels were not used for transportation.\n\n Evidence indicates they were created to serve as potter's wheels around 3500 B.C. in Mesopotamia—300 years before someone figured out to use them for chariots.Jun 17, 2009"

In [7]: gres['description'][0]
Out[7]: 'A Salute to the Wheel | Science | Smithsonian Magazinewww.smithsonianmag.com › science-nature › a-salute-to-the-wheel-31805...About Featured Snippets'

In [8]: 
```

**Expected behavior**
In the code sample above the description should be the title, and viceversa.

**Screenshots**
See code example.

**Desktop (please complete the following information):**

 - Search-engine-parser version [e.g. 0.5.1]
 Development version: `pip install git+https://github.com/bisoncorps/search-engine-parser`

**Comment by MeNsaaH** [comment]
@pgrandinetti  can you make a PR for this?

**Comment by pgrandinetti** [comment]
@MeNsaaH I am not sure where the problem is actually!

**Comment by MeNsaaH** [comment]
https://github.com/bisoncorps/search-engine-parser/blob/954723a97cfd33295099f9accbfe21ef544064da/search_engine_parser/core/engines/google.py#L74

That's where the title is parsed. Maybe you can check it and confirm if the referenced html tags and attributes are correct

**Comment by deven96** [comment]
Check if master now fixes this @pgrandinetti
