### ISSUE TITLE
Running example errors about cache

### ISSUE THREAD

**Issue by gouinK** [bisoncorps/search-engine-parser#139]
Running your example code gives this error (even when I directly specify cache=False in the command).

This command: 
gresults = gsearch.search(query='wat', cache=False)

gives this error:
[Errno 17] File exists: 'cache'

**Comment by deven96** [comment]
Could you give a bit of context @gouinK ?
Library version, OS, e.t.c

**Comment by gouinK** [comment]
Yes so I am running this on Mac OSX

Package version:
search-engine-parser    v0.6.2   

Here is my very short script:

```
import nest_asyncio
nest_asyncio.apply()

import pprint

from search_engine_parser.core.engines.google import Search as GoogleSearch

gsearch = GoogleSearch()
gsearch.clear_cache()
gresults = gsearch.search(query='wat',cache=False)
```

Here is the traceback

---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
<ipython-input-2-8b4eec89b1be> in <module>
      1 gsearch = GoogleSearch()
----> 2 gsearch.clear_cache()
      3 gresults = gsearch.search(query='wat',cache=False)
      4 # gresults = await gsearch.async_search(query='wat',cache=False)
      5 

/opt/anaconda3/envs/searcher/lib/python3.8/site-packages/search_engine_parser/core/base.py in clear_cache(self, all_cache)
    174         if all_cache:
    175             return self.cache_handler.clear()
--> 176         return self.cache_handler.clear(self.name)
    177 
    178     async def get_source(self, url, cache=True, proxy=None, proxy_auth=None):

/opt/anaconda3/envs/searcher/lib/python3.8/site-packages/search_engine_parser/core/base.py in cache_handler(self)
    135     @property
    136     def cache_handler(self):
--> 137         return self.get_cache_handler()
    138 
    139     def parse_result(self, results, **kwargs):

/opt/anaconda3/envs/searcher/lib/python3.8/site-packages/search_engine_parser/core/base.py in get_cache_handler(self)
    131         """ Return Cache Handler to use"""
    132 
--> 133         return utils.CacheHandler()
    134 
    135     @property

/opt/anaconda3/envs/searcher/lib/python3.8/site-packages/search_engine_parser/core/utils.py in __init__(self)
     35     def __init__(self):
     36         if not os.path.exists(os.path.join(FILEPATH, "cache")):
---> 37             os.makedirs("cache")
     38         self.cache = os.path.join(FILEPATH, "cache")
     39         enginelist = os.listdir(os.path.join(FILEPATH, "engines"))

/opt/anaconda3/envs/searcher/lib/python3.8/os.py in makedirs(name, mode, exist_ok)
    221             return
    222     try:
--> 223         mkdir(name, mode)
    224     except OSError:
    225         # Cannot rely on checking for EEXIST, since the operating system

FileExistsError: [Errno 17] File exists: 'cache'
