### ISSUE TITLE
Release 6.0.3 is not available on pypi

### ISSUE THREAD

**Issue by Przemek625** [bisoncorps/search-engine-parser#151]
Currently I can not install new release 6.0.3 with pip because it is not available on pypi.

![image](https://user-images.githubusercontent.com/15988345/133233676-d2f9db0b-62c9-4685-b3aa-d629c46bb688.png)

https://pypi.org/project/search-engine-parser/#history

**Comment by MeNsaaH** [comment]
@deven96  we need to update the deploy scripts to check if the tag and the version are the same.

**Comment by MeNsaaH** [comment]
I've released a newer version and updated the scrpits. Shoudn't happen in future

**Comment by deven96** [comment]
What if we push a tag and it fails to deploy (perhaps cuz test fails), isn't that tag effectively wasted? @MeNsaaH

**Comment by MeNsaaH** [comment]
The tag doesn't run tests. I just deploys

**Comment by deven96** [comment]
> The tag action doesn't run tests. I just deploys

Doesn't that mean we can trigger a tag despite failing tests?

**Comment by MeNsaaH** [comment]
Yeah. But why would you do that? You push a tag when you are comfortable with what is on the branch
