### ISSUE TITLE
Integrate cachelib for caching results

### ISSUE THREAD

**Issue by deven96** [bisoncorps/search-engine-parser#32]
Include options to empty cache

**Comment by MeNsaaH** [comment]
@deven96 how about this

**Comment by deven96** [comment]
We can implement it... shouldn't be too difficult

**Comment by deven96** [comment]
We could instead use the LRU cache from functools.... instead of cachelib

**Comment by MeNsaaH** [comment]
Does it persist to storage?

**Comment by deven96** [comment]
Yeah it does... but we have to work a way for it to persist through multiple class instances

**Comment by MeNsaaH** [comment]
We could use the simple approach like Colly's Cache system. Write to file and check for that before moving on

**Comment by deven96** [comment]
We could.... but then the LRU gives us a way to setup automatic invalidation maybe if we want the cache to be valid for the next 2 days after calling it.... also the clear_cache method comes inbuilt

**Comment by MeNsaaH** [comment]
Alright then

Manasseh Mmadu
