### ISSUE TITLE
Add MyAnimeList Engine

### ISSUE THREAD

**Issue by PalAditya** [bisoncorps/search-engine-parser#37]
**Is your feature request related to a problem? Please describe.**
No, it is a request for a new custom engine, namely *MyAnimeList*.

**Why should it be added?**

From Wikipedia, we have `MyAnimeList, often abbreviated as MAL, is an anime and manga social networking and social cataloging application website. The site provides its users with a list-like system to organize and score anime and manga. It facilitates finding users who share similar tastes and provides a large database on anime and manga. The site claims to have 4.4 million anime and 775,000 manga entries. In 2015, the site received 120 million visitors a month`. Right now, the traffic will be far more and there are projects like [Jikan]([https://github.com/jikan-me/jikan) which are dedicated to this, so this project should definitely include MAL parsing.

**Describe the solution you'd like**

- Initial: Search MAL based on genres only (action, adventure...) and return results. This is well within capabilities of the current design of the base class.
- Later: Allow MAL engine to have extra parameters so that it can search for the *exact* anime, show results from lists such as *most popular* anime, etc.

**Comment by deven96** [comment]
Probably we could discuss it further on the [mailing list](). There is a new contribution guide that encourages discussing new engines and enhancements on the mailing list before raising issues

**Comment by PalAditya** [comment]
Actually, it seems I don't have access to the mailing list as I get
unauthorized (#418) error, so could you change it's settings/add me to it
please?

**Comment by deven96** [comment]
You can join now sorry, permission errors on Google Groups

**Comment by deven96** [comment]
Since we aim to be the largest collection of search engines then an anime catalog would be an awesome addition

**Comment by MeNsaaH** [comment]
@PalAditya, can you make the PR again. We've reverted the PR due to conflicts and changing tests

**Comment by PalAditya** [comment]
I actually haven't  finished incorporating the changes mentioned by @deven96 in #42 , and wouldn't be able to do so for *3-4* days maybe due to my mid-term exams coming up (😅 ), so is it okay if I reopen the PR after that with the changes?

Or should I re-open it as it was previously and you guys would like to improve and incorporate it as per your choice (in case time is critical)? 🤔 

Do let me know either way 😄

**Comment by deven96** [comment]
Reopen the PR as it was initially but take your time incorporating the changes mentioned. Goodluck in your mid terms!

**Comment by MeNsaaH** [comment]
Goodluck in you midterms @PalAditya

**Comment by PalAditya** [comment]
The MAL engine (#45 ) has been updated with your comments @deven96 , so you can have a look at it now if you wish😁
