### ISSUE TITLE
Cannot install from pip3.

### ISSUE THREAD

**Issue by AvinashReddy3108** [bisoncorps/search-engine-parser#39]
**Describe the bug**
Package doesn't install at all.

**To Reproduce**
Steps to reproduce the behaviour:
Trying to install `search-engine-parser>=0.4.2` using pip3 (requirements.txt)

**Expected behaviour**
The package should install.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Alpine Linux (Docker)
 - Python Version: 3.7.4

**Additional context**
Here's the error log.

```
Collecting search-engine-parser>=0.4.2 (from -r requirements.txt (line 33))
  Downloading https://files.pythonhosted.org/packages/ec/56/29a3e6e098674ffef9a12c360275e90146a96bde626f277d329248aafe76/search-engine-parser-0.5.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-shzymtgy/search-engine-parser/setup.py'"'"'; __file__='"'"'/tmp/pip-install-shzymtgy/search-engine-parser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-shzymtgy/search-engine-parser/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-shzymtgy/search-engine-parser/setup.py", line 5, in <module>
        from _version import VERSION
    ModuleNotFoundError: No module named '_version'
    ----------------------------------------
```

**Comment by AvinashReddy3108** [comment]
Maybe [this](https://github.com/dyve/django-bootstrap-toolkit/issues/71#issuecomment-16361764) can help ?

**Comment by MeNsaaH** [comment]
@AvinashReddy3108, try the installation again. A new version with a fixed has being deployed to PyPi

**Comment by deven96** [comment]
@all-contributors Add @AvinashReddy3108 for bug report in issue #39

**Comment by AvinashReddy3108** [comment]
> @AvinashReddy3108, try the installation again. A new version with a fixed has being deployed to PyPi

I did, and it works.
Thanks for the awesome library.

**Comment by MeNsaaH** [comment]
@AvinashReddy3108, put a star on it
