### ISSUE TITLE
Issues with the YouTube engine via CLI

### ISSUE THREAD

**Issue by AvinashReddy3108** [bisoncorps/search-engine-parser#49]
**Describe the bug**
Cannot search YouTube via the pysearch CLI tool.

**To Reproduce**
1. Open Terminal (I installed the latest search-engine-parser via pip.)
2. Execute `pysearch --e youtube search --q "NoCopyrightSounds"`
3. Wait 0 seconds
4. See error: `Engine < youtube > does not exist`

**Expected behavior**
Since NCS is very popular over at YouTube, it should have returned something.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: elementaryOS 5.0 Juno [based on Ubuntu 18.04 - Bionic Beaver]
 - Python Version: 3.6.8 (from the Ubuntu repositories)

**Additional context**
The same goes for the other search engines like, Ask, AOL, Baidu.

**Comment by deven96** [comment]
@AvinashReddy3108, try the installation again. A new version 0.5.3 with a fix has being deployed to PyPi

**Comment by AvinashReddy3108** [comment]
> @AvinashReddy3108, try the defunct engines CLI again. A new version 0.5.3 with a fix has being deployed to PyPi

It works now, thanks for the update.
