### ISSUE TITLE
Create an API for the project

### ISSUE THREAD

**Issue by PalAditya** [bisoncorps/search-engine-parser#55]
**Is your feature request related to a problem? Please describe.**
No, it is an optional *enhancement*

**Describe the solution you'd like**
Create an API for the search-engine-parser package and deploy it to a system like *Heroku*

**Reason**
Right now, the project has quite a few dependencies (which will only grow) and is kind of python-only (using it in a Spring-boot project is possible, but it's not easy), so why can't we create a minimalist flask app version of the library and deploy it to Heroku, so that people who build projects in other languages would also be able to integrate it, or use it directly from command line with ```curl``` or ```wget``` with something like ```curl -i https://searchengineparser.herokuapp.com/{path}```? No hassle of setup either 😄 

I am not saying this has to be an immediate target, but won't it be a nice enhancement/auxiliary feature? @deven96 , @MeNsaaH  what do you think? 🤔 

**Note**
If this is ever taken up, I would love to help with it. Not much changes would be required either (probably 😅 ), since the responses are in a nice, tidy JSON format already :)

**Comment by deven96** [comment]
An awesome idea @PalAditya . We can write the API using a minimalistic framework like flask and deploy to a subdomain on bisoncorps.com. The request should contain the engine name, query and list of returns e.g ["titles", "links"].  Any other propositions concerning the feature

**Comment by PalAditya** [comment]
Not so much *propositions* as much as doubts, but here goes:
- So, for deploying to the subdomain of bisoncorps, we'd probably require a script that would restart the flask server every time a new version is pushed there (which we be automated with GitHub actions probably), I guess?
- Would it be a part of this repository (under say ```/api``` or a separate one?
- What happens when user enters n valid query strings and an invalid one? (for example, ```links, titles and deeeescription```?) {Possiblities: Return results for valid ones and tell user that others are invalid, possible values for that endpoint are ..., or directly return 403 and in info tell them about valid queries} 

I believe this would be sufficient for now. In case you guys decide to create a separate repository, the rest of the discussions can be carried out there, or else you can pin this issue so that other people can find it easily and comment on other feature requests.

**Comment by deven96** [comment]
Sorry for the late reply, my exams take the blame for this ☺
- We can make use of Travis to automate the push to the server. It would be running automation scripts to copy the nginx and gunicorn scripts to the  right locations and restart the services

- I think we are settled for making it part of this repository. A subfolder perhaps but on second thought making it it's own repository might aid the automatic deployment process

- An extra query string can be added to let the user decide what to happen (returm 403 if one of the query strings did not exist or return those that do exist)

What do you think?

**Comment by PalAditya** [comment]
Ah, exams, the same thing that was troubling me a week ago 😂
- Agreed
- Making it part of this repository would probably be the best if it doesn't hamper the pypi packaging process (I don't know how the packaging system works exactly in Python, so you guys would be the best judge of that) as then we can always keep the endpoint updated with whenever a new engine gets added. It could be a part of the release/deploy script. Also, people would have more visibility of it then (Although displaying it brightly in README could mitigate this issue). The only benefit a separate repository would have is that contributing and debugging would probably be easier for newer members. As for my personal preference, it should be a part of this repository.
- Yes, maybe as an options list (which currently will support only that option but later might support others)

**Comment by deven96** [comment]
The life of a student developer

Well it seems we are in agreement. I've pinned this issue and very soon we can start working on it. We will bring you in on the feature

Thanks for the suggestion. You've been of great help!

**Comment by deven96** [comment]
Currently in development in a  separate repository. View  project at [repo](https://github.com/bisoncorps/search-engine-api)

**Comment by PalAditya** [comment]
Awesome! 😄

**Comment by AvinashReddy3108** [comment]
Hey @PalAditya @deven96 
you guys might wanna check this repo out, it's a youtube-dl api server writen in flask.
https://github.com/jaimeMF/youtube-dl-api-server

..it also has a Ready-For-Heroku fork here.
https://github.com/iphoting/youtube-dl-api-server-heroku

Hope this helps with the search-engine-api server stuff.

**Comment by deven96** [comment]
Nice suggestion @AvinashReddy3108 ... pretty sure we can pick up a lot of ideas from there.. Thanks!

**Comment by MeNsaaH** [comment]
The API Engine is complete or stable for now to say. https://github.com/bisoncorps/search-engine-api
