### ISSUE TITLE
Issues in documentation

### ISSUE THREAD

**Issue by PalAditya** [bisoncorps/search-engine-parser#59]
**Describe the bug**
There are few issues in documentation (mostly due to copy/pasting errors), I guess, which must be removed

**To Reproduce**
Go to documentation for [StackOverflow](https://search-engine-parser.readthedocs.io/en/latest/search_engine_parser.core.engines.html#module-search_engine_parser.core.engines.stackoverflow), it says it is a parser for **AOL** and describes **GitHub**

**Additional note**
I will be opening a PR to fix the bug in StackOverflow module, but in the [summary](https://search-engine-parser.readthedocs.io/en/latest/search_engine_parser.core.engines.html#search_engine_parser.core.engines.google.GoogleSearch.summary) parts of docs, there are ugly ```\t\n``` characters. Also, in many cases, the params are not linted nicely (fine [here](https://search-engine-parser.readthedocs.io/en/latest/search_engine_parser.core.engines.html#search_engine_parser.core.engines.googlescholar.GoogleScholarSearch.parse_single_result) but not [here](https://search-engine-parser.readthedocs.io/en/latest/search_engine_parser.core.engines.html#search_engine_parser.core.engines.aol.AolSearch.parse_single_result))

Maybe you guys can create a list of subtasks on this issue, and they can be ticked off as and when these docs related issues are solved?

**Comment by deven96** [comment]
- [ ] Fix StackOverflow class documentation
- [ ] Fix StackOverflow engine summary (replace wrong Github summary)
- [ ] Fix parameter linting issues
