### ISSUE TITLE
Incorrect Links

### ISSUE THREAD

**Issue by mi096684** [bisoncorps/search-engine-parser#69]
when I search through Yahoo, Im getting links like below:

https://r.search.yahoo.com/_ylt=Awr9DWam671dmwsAW2pXNyoA;_ylu=X3oDMTBya2cwZmh2BGNvbG8DZ3ExBHBvcwM1BHZ0aWQDBHNlYwNzcg--/RV=2/RE=1572756518/RO=10/RU=https%3a%2f%2finvestorplace.com%2f2019%2f04%2fmicrosoft-is-no-longer-a-dark-horse-in-race-for-jedi-contract-msft%2f/RK=2/RS=ou7i7WR1VK54zkDix5WcJjVpgsc-

which is supposed to be:
**https://finvestorplace.com/2019/04/microsoft-is-no-longer-a-dark-horse-in-race-for-jedi-contract-msft/**

let me know if Im making any mistakes.

**Comment by deven96** [comment]
Is this issue local to only the Yahoo engine?

**Comment by mi096684** [comment]
I found this issue in Yahoo and DDG

**Comment by deven96** [comment]
Thanks a lot for raising this .... a fix will be provided soon

**Comment by deven96** [comment]
Fixed and deployed a new version 0.5.4
@all-contributors add @mi096684 for bug contributions
