### ISSUE TITLE
This event loop is already running

### ISSUE THREAD

**Issue by d1sharma** [bisoncorps/search-engine-parser#72]
**Describe the bug**
Hi when I tried to search for this sentence, it throws me a bug:
This event loop is already running

Code below:
from search_engine_parser import GoogleSearch,BingSearch,YahooSearch
query = "spider president ” president bill clinton filthy rich story financier jeffrey epstein years revelations arrest suicide"
gsearch = GoogleSearch()
args=(query,1)

try:
    gr = gsearch.search(*args)
except Exception as e:
    print(e)

**Expected behavior**
This event loop is already running

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Python Version [ 3.7.3]
 - Search-engine-parser version [0.5.3.post3]

**Additional context**

**Comment by MeNsaaH** [comment]
@d1sharma can you provide a stack trace of the error displayed on the terminal

**Comment by AvinashReddy3108** [comment]
`The event loop is already running` errors pop up only if you use the `gsearch.search(*args)` method under an async function (makes sense that way.) In that case you must replace `gsearch.search(*args)` with `gsearch.async_search(*args)`.

Here's my code in production as an example.

Snippet : [HERE](https://github.com/AvinashReddy3108/PaperplaneExtended/blob/master/userbot/modules/scrapers.py#L182-L213)
Using the ASync Search method : [HERE](https://github.com/AvinashReddy3108/PaperplaneExtended/blob/master/userbot/modules/scrapers.py#L195)

Hope this helps.

**Comment by MeNsaaH** [comment]
@AvinashReddy3108, Thanks for your explanation. It's should be clear to people the difference and use cases of `async_search` and `search`. Care to make a PR for that?

**Comment by AvinashReddy3108** [comment]
> @AvinashReddy3108, Thanks for your explanation. It's should be clear to people the difference and use cases of `async_search` and `search`. Care to make a PR for that?

In the README.md?
I'll be happy to!

**Comment by MeNsaaH** [comment]
Yeah, @AvinashReddy3108. To the README. Thanks
