### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by anon97945** [bisoncorps/search-engine-parser#88]
**Is your feature request related to a problem? Please describe.**
i cant use the parser for searching google.de

**Describe the solution you'd like**
i want to be able to set a localization to use google.fr or google.de or whatever

**Describe alternatives you've considered**

**Additional context**
I would like to give it a localization to use it for other results...

regards

**Comment by MeNsaaH** [comment]
@anon97945, looks like a great feature. Care to make a PR?
