### ISSUE TITLE
Access rights: permission denied

### ISSUE THREAD

**Issue by melshelly** [bisoncorps/search-engine-parser#91]
Dear Search engine parser team,

From the Windows 10 command line, I successfully used pip to install search-engine-parser and search-engine-parser[cli]. However, when trying to clone this repository, git clone git@github.com:bisoncorps/search-engine-parser.git, I receive the following for search-engine-parser 0.6:

Cloning into 'search-engine-parser'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I have installed Python 3.8.3, by the way.

Thanks for your help.

**Comment by MeNsaaH** [comment]
@melshelly clone with the `https` repo link instead https://github.com/bisoncorps/search-engine-parser.git and it should work
